# Generated by Django 4.0.6 on 2022-07-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
